shpakovski/MASShortcut

- .travis.yml
- MASShortcut.xcodeproj/xcshareddata/xcschemes/Demo.xcscheme
- MASShortcut.xcodeproj/xcshareddata/xcschemes/MASShortcut.xcscheme
This will build the project and run the tests each time the repo changes. We’ll also get a nice green badge on all pull requests if they pass the test suite and the same badge also appears in CocoaDocs. The changes are pretty simple and non-intrusive.
@shpakovski, can you please log in to [Travis](https://travis-ci.org/) and add the official MASShortcut repo there? I can’t add the official repo as a collaborator, but I’ve tested on my fork. Then you can merge the PR and see the green light coming up :)
> Add support for Travis Continuous Integration server

- README.md
The explicit Cocoa import had tripped me up. Would be good to save someone the same hassle.
> Added explicit instructions for use in Swift

- CHANGES
- Demo/MainMenu.xib
- Framework/MASHotKey.m
- Framework/MASHotKeyTests.m
- Framework/MASShortcutMonitor.h
- Framework/MASShortcutMonitor.m
- Framework/MASShortcutMonitorTests.m
- Framework/MASShortcutView.m
- MASShortcut.podspec
- MASShortcut.xcodeproj/project.pbxproj
Adds support for OS X down to 10.6 included. Mostly just two changes: removed Auto Layout support in the demo project and replaced `__weak` (unsupported on 10.6) with `__unsafe_unretained`. As both instances of `__weak` were used to prevent retain cycles, I think the changes should be safe.
@shpakovski, would you like to go over the changes before merging? You have already seen b9b1964, the two other commits are also very simple.
> Legacy OS X support down to 10.6 included

- Framework/MASKeyCodes.h
- Framework/MASShortcut.modulemap
- MASShortcut.xcodeproj/project.pbxproj
- README.md
I use [Carthage](https://github.com/Carthage/Carthage) to check out my dependencies and build them as dynamic frameworks.
This tweaks the framework target to make it build with `xcodebuild` and export a `MASShortcut` module that can be imported from Swift.
It also adds a Carthage badge to the README, but that's not important and can be reverted if you like.
Thanks for MASShortcut!
> Support installation with Carthage

- Framework/MASKeyCodes.h
Not declaring this enum variable in the header prevents a duplicate symbols error:
```
duplicate symbol _MASShortcutGlyph in:
/Users/pfandrade/Library/Developer/Xcode/DerivedData/Secrets-epbzwbmqvrgyjjgumbwsgmobfykd/Build/Intermediates/Secrets.build/Debug/Secrets Helper.build/Objects-normal/x86_64/Constants.o
/Users/pfandrade/Library/Developer/Xcode/DerivedData/Secrets-epbzwbmqvrgyjjgumbwsgmobfykd/Build/Intermediates/Secrets.build/Debug/Secrets Helper.build/Objects-normal/x86_64/AppDelegate.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
> Not declaring MASShortcutGlyph as a variable in the header

- Framework/MASLocalization.m
- MASShortcut.podspec
Puts strings inside a MASShortcut resource bundle, and looks for locallized strings inside that bundle when used as a CocoaPod.
I tested this is a new vanilla project using CocoaPods and my local repo.
Fixes the issue I raised in #74.
> fixes localized strings when using CocoaPods

- Framework/MASKeyCodes.h
- Framework/MASShortcutView.h
- Framework/MASShortcutView.m
This PR introduces two changes:
- Improves Swift syntax when dealing with enumerations in the project by using `typedef NS_ENUM`
- Fixes an expected non-null return string from the NSToolTip method implemented in `MASShortcutView`
> Minor fixes and Swift improvements

- MASShortcut.xcodeproj/project.pbxproj
I ran into some trouble using MASShortcut alongside `@IBDesignable` in Xcode tonight, and noticed that the `INSTALL_PATH` had been hard-coded to `"@executable_path/../Frameworks"` and the `DYLIB_INSTALL_NAME_BASE` was defaulting to `/Library/Frameworks`.
Since Mac OS X 10.5, setting `DYLIB_INSTALL_NAME_PATH` to `@rpath` has been the preferred setting - this allows apps and other frameworks to ask the dynamic linker to search a specific list of locations (set using the `LD_RUNPATH_SEARCH_PATHS` variable), rather than hard coding the list of places into the library.
There's more info at https://www.mikeash.com/pyblog/friday-qa-2009-11-06-linking-and-install-names.html, but it resolved the Interface Builder issues I was having, and these settings are the defaults when you create a new macOS …
> Set DYLIB_INSTALL_NAME_BASE to @rpath

- Demo/pt.lproj/Localizable.strings
- MASShortcut.xcodeproj/project.pbxproj
- pt.lproj/Localizable.strings
Brazilian Portuguese localization taking in consideration space constraints usually imposed by shortcut recording interfaces.
Please note that Apple has been using pt.lproj for Brazilian Portuguese and pt-PT for European Portuguese, thus the locale creation on Xcode.
Also note that in the string: "… most shortcuts can be changed in the Keyboard & Mouse panel in System Preferences", the correct path should be Keyboard, as this pane has been split in two for a while on macOS.
> Brazilian Portuguese localization

- Framework/MASShortcut.m
kVK_ANSI_KeypadMinus should return regular HYPHEN-MINUS (45) symbol instead of provided EN DASH (8211).
> kVK_ANSI_KeypadMinus value adjustment.

- Framework/MASShortcutView.m
In `MASShortcutView.m`, `-activateEventMonitoring:` was implicitly retaining self in two places by using the `_shortcutValidator` variable. In certain cases, this caused the control to fail to recognize new keystrokes.
To see the problem in action, run the attached sample project. Click shortcut view, then press command-w to close the window (before a shortcut has been set). Open a new document window and click the shortcut view there - at this point modifier keys will not register in the view.
The reason seems to be that because self is retained buy the block, when the new control calls `-activateEventMonitoring:`, the old block and therefore the old self is dealloc'ed, which causes `activateEventMonitoring:` to be called a second time with `NO`. …
> Remove implicit retain of self in eventMonitor block

- Framework/MASShortcutView.m
I've updated the code as suggested by Xcode 9; of particular note, there a couple of commas that should be semicolons.
> Replace commas with semicolons to separate statements

- Framework/MASShortcutView.m
Adds a basic intrinsicContentSize for auto layout compatibility.  
Uses a fixed width, as it seems that providing an accurate intrinsic width would require refactoring the code which is more effort than I want to put into this.  But I think that would be the way to go in order to do this properly.
> Provide intrinsicContenSize to improve compatibility with autolayout

- Framework/MASShortcut.h
- Framework/MASShortcut.m
- Framework/MASShortcutValidator.m
It was initially suggested in #103 that we change -keyCode to NSInteger and -modifierFlags to NSEventModifierFlags, but the changes were mixed with other unrelated stuff and the discussion died out. But the main point of the proposed patch was good, the suggested types make the code work better in Swift, apart from other things.
> Use more specific types for -keyCode and -modifierFlags

- Framework/MASShortcutView.m
Previously, setting a nil `shortcutValidator` on `MASShortcutView` would lead to all shortcuts considered invalid. I think it’s better the other way around, where setting “no validator” means the caller wants no validation done at all.
(I actually have a use case for this. Under normal circumstances, recording keys with no validation doesn’t have much sense, but I use `MASShortcutView` to record shortcuts that will be used in a different context, in the browser.)
> Make it possible to turn off shortcut validation

- .travis.yml
- HACKING.md
- MASShortcut.podspec
- MASShortcut.xcodeproj/project.pbxproj
- README.md
There was a trivial error in the podspec that prevented the CocoaPods build from succeeding (see #131), now we should be back in the game. I have also tried adding a CocoaPods linter pass into Travis config to make sure we keep the CocoaPods build working.
> Fix CocoaPods build

- Framework/Model/MASShortcut.h
- Framework/UI/MASShortcutView+Bindings.h
- Framework/UI/MASShortcutView.h
These are some basic annotations (see #102) that mostly make it easier to use MASShortcut from Swift, since the properties no longer show up as suspect implicitly unwrapped optionals. I did not annotate all the classes, just the main ones that most people will use.
> Add nullability annotations

- Resources/it.lproj/Localizable.strings
Use the word 'abbreviazione' instead of 'scorciatoia' as Apple's translations.
Fix accent (perchè -> perché).
Use a less formal formal style as in Apple's menu.
> Update Italian translation

- Framework/UI/MASShortcutView.h
- Framework/UI/MASShortcutView.m
NSBezelStyleRegularSquare is drawn properly on macOS 11.0.
I'd use this style as a quick fix for #149. 
macOS **11.0**:
macOS **10.15**:
Not ideal, might want to conditionally use another style before 11.0.
> Added regularSquare style to MASShortcutView

- Framework/UI/MASShortcutView.m
This makes it possible to select it using VoiceOver and prevents the system from ignoring the accessibility notification that's posted when the shortcut is changed.
> Make MASShortcutView an accessibility element. #152

- Framework/UI/MASShortcutView.m
A small typo was introduced recently when deprecated constants were replaced with their new names. An instance of `NSOnState` was accidentally converted to `NSControlStateValueOff` instead of `NSControlStateValueOn`.
> Fix typo from replacement of deprecated constants

- Framework/Model/MASKeyCodes.h
- Framework/Model/MASShortcut.m
My use case involves setting `keyCodeStringForKeyEquivalent`s of `MASShortcut`s directly into `NSButton`s' `keyEquivalent` properties.
`MASShortcut` class can help simplify display logic for special function keys such as "←". However, I found that `keyCodeStringForKeyEquivalent`s of functions keys such as arrow, backspace, return and alike returns empty.
This PR:
1. Removes `keyCodeString.length <= 1` testing in `-[MASShortcut keyCodeStringForKeyEquivalent]` since only `keyCodeString`s of F keys contains multiple charactes.
2. Makes `keyCodeStringForKeyEquivalent` aligned up with `keyCodeString`. All keys are tested and should work, **except for space and tab**.
* Using space for keyEquivalent is not supported by AppKit, see [here](https://stackoverflow.com/questions/11155239/nsmenuitem-ke …
> Support for generating correct keyEquivalents for function keys.
